@Restaurent.API_HostAddress = https://localhost:7150
@token = CfDJ8K13CdwTVX1PtGpDupX5ughag1Rjpx4eTcTDfniHHa-OyEuLg969-u1RP8lcgjlluGOq7R052XRNDSuwemVXNi8Jlew57u-yxJllO31Cs_HU9-a7CXZzW7960kOlO2IM9srgaVsg4gkRPquBrLrR3Tfe9IcxxZMq8NSemtC1PnTPT6wx1FmvBnJqk61O4KVxgpv9WPbepi-JzGxNqqp2WX9NuVcC6xyEvB898ins1uKqcZvP8KDy0_keE6aEVmB2a7Lb7yqgJIj3kQrV4gWYS82LMTsPvDuVE-ivivNrAKCwyCQnjPJM4Az52K-kF-t4TSeFyaIgVioNJkxWKBP6c0W6EIYtCw_WUyOXWYhKftB3Kh19LiUlUG3U04z4-kwNRa4uNlGhm2S3hmYfvQdTCsk-JROtZjXklFKGioCcQGmD2OkBMHzfFQwYzd_c4-8JeFsOgSyNn4ajT0JF2NPVlt5fGZH1PqgkI2zZoepUkYylLR7n8dZa5pMG51604hQg3j-5ePHe8gIfLHrY_jTRjH-q2uD1-OcekF6z7aRi7KqQhCtJ7HVXnTwC3G2NjGaLsSDUqLf7Ups2leZn3PD8YpjO2YOYrvC5qMfSjCUfJKc--tXdRO7L9Gr26XwMKKTxBhZe3YKkA3LoZNoWQrC6oJ49aAUh2OqDQZpBIbKb8hjHtUvVIWOIhOLwpja4oXDurf7Fn9rnZNjs_wg_JB5WWvKq7Xnu9JUT7J6kIJRVbvBjMw0i7dyZnwxP6Tm5vDKcr1rrFS1NjdOxCnMSW2-ybdwanHtxs57iTmFz982t8_ge

GET {{Restaurent.API_HostAddress}}/api/restaurants?searchparam=kfc&pageSize=5&pageNumber=1
Authorization: Bearer {{token}}
###

GET {{Restaurent.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
###

Post {{Restaurent.API_HostAddress}}/api/restaurants/
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Name" : "Spicy Chowmein",
    "Category": "Chinese",
    "ContactEmail": "abheesh",
    "ContactNumber": "02222",
    "PostalCode": "55-420",
    "ContactEmail" : "owner@gmail.com"
}

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/30
Authorization: Bearer {{token}}
###

PATCH {{Restaurent.API_HostAddress}}/api/restaurants/99
Content-Type: application/json
{
    "Name": "Dummy Test",
    "Description": "Dummy Description",
    "HasDelivery": true
}

###

POST {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Name": "Spicy Chowmein",
    "Description" : "Thick and Fullfilling",
    "Price": 40
}

###

GET {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes

###

GET {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes/10

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes/10

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes

###

POST {{Restaurent.API_HostAddress}}/api/identity/register
Content-Type:Application/json
{
    "email" : "testuser@test.com",
    "password": "Password123!"
}

###

POST {{Restaurent.API_HostAddress}}/api/identity/login
Content-Type: Application/json
{
    "email" : "owner@test.com",
    "password": "Password123!"
}

###

PATCH {{Restaurent.API_HostAddress}}/api/identity/user
Content-Type: Application/json
{
    "DateofBirth": "2001-01-01",
    "Nationality": "pakistani"
}
###

POST {{Restaurent.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: Application/json
{
    "UserEmail" : "testuser@test.com",
    "RoleName": "user"
}

###

DELETE {{Restaurent.API_HostAddress}}/api/identity/removeUserRole
Authorization: Bearer {{token}}
Content-Type: Application/json
{
    "UserEmail" : "testuser@test.com",
    "RoleName": "user"
}

###