@Restaurent.API_HostAddress = https://localhost:7150

GET {{Restaurent.API_HostAddress}}/api/restaurants

###

GET {{Restaurent.API_HostAddress}}/api/restaurants/2

###

Post {{Restaurent.API_HostAddress}}/api/restaurants/
Content-Type: application/json

{
    "Name" : "Ching Chong",
    "Category": "Chinese",
    "ContactEmail": "abheesh",
    "ContactNumber": "02222",
    "PostalCode": "55-420",
    "ContactEmail" : "abhesh@gmail.com"
}

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/2

###

PATCH {{Restaurent.API_HostAddress}}/api/restaurants/99
Content-Type: application/json
{
    "Name": "Dummy Test",
    "Description": "Dummy Description",
    "HasDelivery": true
}

###