@Restaurent.API_HostAddress = https://localhost:7150
@token = CfDJ8K13CdwTVX1PtGpDupX5ugg6z2n0_PwnEb5_ozrZ6JJF_b1mf5YthsEu25ROH9H7aejspN2xalGSgvN4h5VfaZ2eNLreP5qGDGUY-leixcpDMk64In6VfLbw3QM1O4vCcW93Ad5cupKJRxjDf7kLAhAYqUW7bzuIsxssCdas1QddTavX6EJZzJIrN513nqL5xFIIrYgLTTLWwCqKu9IxSlGKp73WiH6RU4t9rgjHyZ-m_-mY4QsEB3PtT1Vk4qnyUvhi4BoABS_N-0fvzhXUusw8wTFucBdb5Ju257QBoct1380XpTq7SlRcXgE8TiGZSeOdCg4_HmDbt3M_B6ZMWxQKj_2_htv7vPh1sajB7tUcr58vjFN2ZKIKDvZBMeExiCLXn5Jnc9V2sUE5MT01SrOcaz8gEm0pjnzfCbUtwVcq8dAPug8DxATJR-VKoGUOJWSW6Xbl2mFP3y015bv5vr6r29mbNzdvCvMNBn3weCYpFxsy7f0HbpCIdMyCUu_8ED9hFzzTcti6oXZw7I159yzp8ZMR0KrSFr-8ryNi7eqXvUEHZSP4GaQOKHv_2TG2rWWEubuSte2vo0Hjj48oljVC4HSkJhfLK9zF9XPhla6ckVpBwUplof1ZPDII6oZi5x8uyRYywQ0b_SB4cu6ewZEQqgnU95iHfKh3sa6f4Cjjjv_uEh-9Fj_EpNW2oe3NWLhGVBR49lrfVqzxcOcG8b-LpsJ9WGi5KZeXej27dtNMmZ1CM9yT82N-oMIMZ7ExamlaA8N6d4jbmO3wv2tYWsOtCZq0VL4ZqbCZWiPclJpX

GET {{Restaurent.API_HostAddress}}/api/restaurants?searchParam=&pageSize=5&pageNumber=1&sortBy=Name&sortdirection=Desc
Authorization: Bearer {{token}}
###

GET {{Restaurent.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
###

Post {{Restaurent.API_HostAddress}}/api/restaurants/
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Name" : "Zinc Drink",
    "Category": "Ziscy",
    "ContactEmail": "abheesh",
    "ContactNumber": "02222",
    "PostalCode": "55-420",
    "ContactEmail" : "owner@gmail.com"
}

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/30
Authorization: Bearer {{token}}
###

PATCH {{Restaurent.API_HostAddress}}/api/restaurants/99
Content-Type: application/json
{
    "Name": "Dummy Test",
    "Description": "Dummy Description",
    "HasDelivery": true
}

###

POST {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Name": "Spicy Chowmein",
    "Description" : "Thick and Fullfilling",
    "Price": 40
}

###

GET {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes

###

GET {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes/10

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes/10

###

DELETE {{Restaurent.API_HostAddress}}/api/restaurants/20/dishes

###

POST {{Restaurent.API_HostAddress}}/api/identity/register
Content-Type:Application/json
{
    "email" : "testuser@test.com",
    "password": "Password123!"
}

###

POST {{Restaurent.API_HostAddress}}/api/identity/login
Content-Type: Application/json
{
    "email" : "owner@test.com",
    "password": "Password123!"
}

###

PATCH {{Restaurent.API_HostAddress}}/api/identity/user
Content-Type: Application/json
{
    "DateofBirth": "2001-01-01",
    "Nationality": "pakistani"
}
###

POST {{Restaurent.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: Application/json
{
    "UserEmail" : "testuser@test.com",
    "RoleName": "user"
}

###

DELETE {{Restaurent.API_HostAddress}}/api/identity/removeUserRole
Authorization: Bearer {{token}}
Content-Type: Application/json
{
    "UserEmail" : "testuser@test.com",
    "RoleName": "user"
}

###